// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: kits/auth/proto/pb/auth.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Authentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0}
}

type Authentication_Form struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Authentication_Form) Reset() {
	*x = Authentication_Form{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form) ProtoMessage() {}

func (x *Authentication_Form) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form.ProtoReflect.Descriptor instead.
func (*Authentication_Form) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0}
}

type Authentication_Form_AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UnionID string `protobuf:"bytes,2,opt,name=UnionID,proto3" json:"UnionID,omitempty"`
}

func (x *Authentication_Form_AccountInfo) Reset() {
	*x = Authentication_Form_AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_AccountInfo) ProtoMessage() {}

func (x *Authentication_Form_AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_AccountInfo.ProtoReflect.Descriptor instead.
func (*Authentication_Form_AccountInfo) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Authentication_Form_AccountInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Authentication_Form_AccountInfo) GetUnionID() string {
	if x != nil {
		return x.UnionID
	}
	return ""
}

type Authentication_Form_LoginAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *Authentication_Form_LoginAccount) Reset() {
	*x = Authentication_Form_LoginAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_LoginAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_LoginAccount) ProtoMessage() {}

func (x *Authentication_Form_LoginAccount) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_LoginAccount.ProtoReflect.Descriptor instead.
func (*Authentication_Form_LoginAccount) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Authentication_Form_LoginAccount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Authentication_Form_LoginAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Authentication_Form_MobilePhoneSMSCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *Authentication_Form_MobilePhoneSMSCode) Reset() {
	*x = Authentication_Form_MobilePhoneSMSCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_MobilePhoneSMSCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_MobilePhoneSMSCode) ProtoMessage() {}

func (x *Authentication_Form_MobilePhoneSMSCode) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_MobilePhoneSMSCode.ProtoReflect.Descriptor instead.
func (*Authentication_Form_MobilePhoneSMSCode) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Authentication_Form_MobilePhoneSMSCode) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Authentication_Form_MobilePhoneSMSCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Authentication_Form_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme string `protobuf:"bytes,1,opt,name=Scheme,proto3" json:"Scheme,omitempty"`
	// Types that are assignable to Payload:
	//	*Authentication_Form_Login_Account
	//	*Authentication_Form_Login_SMS
	Payload isAuthentication_Form_Login_Payload `protobuf_oneof:"Payload"`
}

func (x *Authentication_Form_Login) Reset() {
	*x = Authentication_Form_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_Login) ProtoMessage() {}

func (x *Authentication_Form_Login) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_Login.ProtoReflect.Descriptor instead.
func (*Authentication_Form_Login) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Authentication_Form_Login) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (m *Authentication_Form_Login) GetPayload() isAuthentication_Form_Login_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Authentication_Form_Login) GetAccount() *Authentication_Form_LoginAccount {
	if x, ok := x.GetPayload().(*Authentication_Form_Login_Account); ok {
		return x.Account
	}
	return nil
}

func (x *Authentication_Form_Login) GetSMS() *Authentication_Form_MobilePhoneSMSCode {
	if x, ok := x.GetPayload().(*Authentication_Form_Login_SMS); ok {
		return x.SMS
	}
	return nil
}

type isAuthentication_Form_Login_Payload interface {
	isAuthentication_Form_Login_Payload()
}

type Authentication_Form_Login_Account struct {
	Account *Authentication_Form_LoginAccount `protobuf:"bytes,2,opt,name=Account,proto3,oneof"`
}

type Authentication_Form_Login_SMS struct {
	SMS *Authentication_Form_MobilePhoneSMSCode `protobuf:"bytes,3,opt,name=SMS,proto3,oneof"`
}

func (*Authentication_Form_Login_Account) isAuthentication_Form_Login_Payload() {}

func (*Authentication_Form_Login_SMS) isAuthentication_Form_Login_Payload() {}

type Authentication_Form_LoginRelpy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme  string                           `protobuf:"bytes,1,opt,name=Scheme,proto3" json:"Scheme,omitempty"`
	Account *Authentication_Form_AccountInfo `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *Authentication_Form_LoginRelpy) Reset() {
	*x = Authentication_Form_LoginRelpy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_LoginRelpy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_LoginRelpy) ProtoMessage() {}

func (x *Authentication_Form_LoginRelpy) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_LoginRelpy.ProtoReflect.Descriptor instead.
func (*Authentication_Form_LoginRelpy) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Authentication_Form_LoginRelpy) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Authentication_Form_LoginRelpy) GetAccount() *Authentication_Form_AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type Authentication_Form_Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme string `protobuf:"bytes,1,opt,name=Scheme,proto3" json:"Scheme,omitempty"`
	// Types that are assignable to Payload:
	//	*Authentication_Form_Register_Account
	//	*Authentication_Form_Register_SMS
	//	*Authentication_Form_Register_CheckUsername
	Payload isAuthentication_Form_Register_Payload `protobuf_oneof:"Payload"`
}

func (x *Authentication_Form_Register) Reset() {
	*x = Authentication_Form_Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_Register) ProtoMessage() {}

func (x *Authentication_Form_Register) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_Register.ProtoReflect.Descriptor instead.
func (*Authentication_Form_Register) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 5}
}

func (x *Authentication_Form_Register) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (m *Authentication_Form_Register) GetPayload() isAuthentication_Form_Register_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Authentication_Form_Register) GetAccount() *Authentication_Form_RegisterAcount {
	if x, ok := x.GetPayload().(*Authentication_Form_Register_Account); ok {
		return x.Account
	}
	return nil
}

func (x *Authentication_Form_Register) GetSMS() *Authentication_Form_MobilePhoneSMSCode {
	if x, ok := x.GetPayload().(*Authentication_Form_Register_SMS); ok {
		return x.SMS
	}
	return nil
}

func (x *Authentication_Form_Register) GetCheckUsername() *Authentication_Form_RegisterCheckUsername {
	if x, ok := x.GetPayload().(*Authentication_Form_Register_CheckUsername); ok {
		return x.CheckUsername
	}
	return nil
}

type isAuthentication_Form_Register_Payload interface {
	isAuthentication_Form_Register_Payload()
}

type Authentication_Form_Register_Account struct {
	Account *Authentication_Form_RegisterAcount `protobuf:"bytes,2,opt,name=Account,proto3,oneof"`
}

type Authentication_Form_Register_SMS struct {
	SMS *Authentication_Form_MobilePhoneSMSCode `protobuf:"bytes,3,opt,name=SMS,proto3,oneof"`
}

type Authentication_Form_Register_CheckUsername struct {
	CheckUsername *Authentication_Form_RegisterCheckUsername `protobuf:"bytes,4,opt,name=CheckUsername,proto3,oneof"`
}

func (*Authentication_Form_Register_Account) isAuthentication_Form_Register_Payload() {}

func (*Authentication_Form_Register_SMS) isAuthentication_Form_Register_Payload() {}

func (*Authentication_Form_Register_CheckUsername) isAuthentication_Form_Register_Payload() {}

type Authentication_Form_RegisterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme string `protobuf:"bytes,1,opt,name=Scheme,proto3" json:"Scheme,omitempty"`
	// Types that are assignable to Payload:
	//	*Authentication_Form_RegisterReply_SMS
	//	*Authentication_Form_RegisterReply_Account
	//	*Authentication_Form_RegisterReply_CheckUsername
	Payload isAuthentication_Form_RegisterReply_Payload `protobuf_oneof:"Payload"`
}

func (x *Authentication_Form_RegisterReply) Reset() {
	*x = Authentication_Form_RegisterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_RegisterReply) ProtoMessage() {}

func (x *Authentication_Form_RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_RegisterReply.ProtoReflect.Descriptor instead.
func (*Authentication_Form_RegisterReply) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 6}
}

func (x *Authentication_Form_RegisterReply) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (m *Authentication_Form_RegisterReply) GetPayload() isAuthentication_Form_RegisterReply_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Authentication_Form_RegisterReply) GetSMS() *Authentication_Form_MobilePhoneSMSCode {
	if x, ok := x.GetPayload().(*Authentication_Form_RegisterReply_SMS); ok {
		return x.SMS
	}
	return nil
}

func (x *Authentication_Form_RegisterReply) GetAccount() *Authentication_Form_AccountInfo {
	if x, ok := x.GetPayload().(*Authentication_Form_RegisterReply_Account); ok {
		return x.Account
	}
	return nil
}

func (x *Authentication_Form_RegisterReply) GetCheckUsername() *Authentication_Form_RegisterCheckUsernameReply {
	if x, ok := x.GetPayload().(*Authentication_Form_RegisterReply_CheckUsername); ok {
		return x.CheckUsername
	}
	return nil
}

type isAuthentication_Form_RegisterReply_Payload interface {
	isAuthentication_Form_RegisterReply_Payload()
}

type Authentication_Form_RegisterReply_SMS struct {
	SMS *Authentication_Form_MobilePhoneSMSCode `protobuf:"bytes,2,opt,name=SMS,proto3,oneof"`
}

type Authentication_Form_RegisterReply_Account struct {
	Account *Authentication_Form_AccountInfo `protobuf:"bytes,3,opt,name=Account,proto3,oneof"`
}

type Authentication_Form_RegisterReply_CheckUsername struct {
	CheckUsername *Authentication_Form_RegisterCheckUsernameReply `protobuf:"bytes,4,opt,name=CheckUsername,proto3,oneof"`
}

func (*Authentication_Form_RegisterReply_SMS) isAuthentication_Form_RegisterReply_Payload() {}

func (*Authentication_Form_RegisterReply_Account) isAuthentication_Form_RegisterReply_Payload() {}

func (*Authentication_Form_RegisterReply_CheckUsername) isAuthentication_Form_RegisterReply_Payload() {
}

type Authentication_Form_RegisterAcount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Phone     string `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PhoneCode string `protobuf:"bytes,4,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
}

func (x *Authentication_Form_RegisterAcount) Reset() {
	*x = Authentication_Form_RegisterAcount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_RegisterAcount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_RegisterAcount) ProtoMessage() {}

func (x *Authentication_Form_RegisterAcount) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_RegisterAcount.ProtoReflect.Descriptor instead.
func (*Authentication_Form_RegisterAcount) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 7}
}

func (x *Authentication_Form_RegisterAcount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Authentication_Form_RegisterAcount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Authentication_Form_RegisterAcount) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Authentication_Form_RegisterAcount) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

type Authentication_Form_RegisterCheckUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *Authentication_Form_RegisterCheckUsername) Reset() {
	*x = Authentication_Form_RegisterCheckUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_RegisterCheckUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_RegisterCheckUsername) ProtoMessage() {}

func (x *Authentication_Form_RegisterCheckUsername) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_RegisterCheckUsername.ProtoReflect.Descriptor instead.
func (*Authentication_Form_RegisterCheckUsername) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 8}
}

func (x *Authentication_Form_RegisterCheckUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Authentication_Form_RegisterCheckUsernameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *Authentication_Form_RegisterCheckUsernameReply) Reset() {
	*x = Authentication_Form_RegisterCheckUsernameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication_Form_RegisterCheckUsernameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication_Form_RegisterCheckUsernameReply) ProtoMessage() {}

func (x *Authentication_Form_RegisterCheckUsernameReply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_auth_proto_pb_auth_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication_Form_RegisterCheckUsernameReply.ProtoReflect.Descriptor instead.
func (*Authentication_Form_RegisterCheckUsernameReply) Descriptor() ([]byte, []int) {
	return file_kits_auth_proto_pb_auth_proto_rawDescGZIP(), []int{0, 0, 9}
}

func (x *Authentication_Form_RegisterCheckUsernameReply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

var File_kits_auth_proto_pb_auth_proto protoreflect.FileDescriptor

var file_kits_auth_proto_pb_auth_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xec, 0x09, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xd9, 0x09, 0x0a, 0x04, 0x46, 0x6f, 0x72, 0x6d, 0x1a,
	0x37, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x1a, 0x46, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x1a, 0x3e, 0x0a, 0x12, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x53,
	0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x1a, 0xac, 0x01, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x03, 0x53, 0x4d, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x2e, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x53, 0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52,
	0x03, 0x53, 0x4d, 0x53, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x63, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x6c, 0x70, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x88, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3e, 0x0a,
	0x03, 0x53, 0x4d, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x2e, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x53,
	0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x03, 0x53, 0x4d, 0x53, 0x12, 0x55, 0x0a,
	0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x8f, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x03, 0x53, 0x4d, 0x53,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x2e,
	0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x53, 0x4d, 0x53, 0x43, 0x6f,
	0x64, 0x65, 0x48, 0x00, 0x52, 0x03, 0x53, 0x4d, 0x53, 0x12, 0x3f, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x5a, 0x0a, 0x0d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x32, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x1a, 0x7c, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x1a,
	0x33, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x2c, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x4f, 0x4b, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x61, 0x61, 0x2f, 0x6b, 0x69,
	0x74, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kits_auth_proto_pb_auth_proto_rawDescOnce sync.Once
	file_kits_auth_proto_pb_auth_proto_rawDescData = file_kits_auth_proto_pb_auth_proto_rawDesc
)

func file_kits_auth_proto_pb_auth_proto_rawDescGZIP() []byte {
	file_kits_auth_proto_pb_auth_proto_rawDescOnce.Do(func() {
		file_kits_auth_proto_pb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_kits_auth_proto_pb_auth_proto_rawDescData)
	})
	return file_kits_auth_proto_pb_auth_proto_rawDescData
}

var file_kits_auth_proto_pb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kits_auth_proto_pb_auth_proto_goTypes = []interface{}{
	(*Authentication)(nil),                                 // 0: pb.Authentication
	(*Authentication_Form)(nil),                            // 1: pb.Authentication.Form
	(*Authentication_Form_AccountInfo)(nil),                // 2: pb.Authentication.Form.AccountInfo
	(*Authentication_Form_LoginAccount)(nil),               // 3: pb.Authentication.Form.LoginAccount
	(*Authentication_Form_MobilePhoneSMSCode)(nil),         // 4: pb.Authentication.Form.MobilePhoneSMSCode
	(*Authentication_Form_Login)(nil),                      // 5: pb.Authentication.Form.Login
	(*Authentication_Form_LoginRelpy)(nil),                 // 6: pb.Authentication.Form.LoginRelpy
	(*Authentication_Form_Register)(nil),                   // 7: pb.Authentication.Form.Register
	(*Authentication_Form_RegisterReply)(nil),              // 8: pb.Authentication.Form.RegisterReply
	(*Authentication_Form_RegisterAcount)(nil),             // 9: pb.Authentication.Form.RegisterAcount
	(*Authentication_Form_RegisterCheckUsername)(nil),      // 10: pb.Authentication.Form.RegisterCheckUsername
	(*Authentication_Form_RegisterCheckUsernameReply)(nil), // 11: pb.Authentication.Form.RegisterCheckUsernameReply
}
var file_kits_auth_proto_pb_auth_proto_depIdxs = []int32{
	3,  // 0: pb.Authentication.Form.Login.Account:type_name -> pb.Authentication.Form.LoginAccount
	4,  // 1: pb.Authentication.Form.Login.SMS:type_name -> pb.Authentication.Form.MobilePhoneSMSCode
	2,  // 2: pb.Authentication.Form.LoginRelpy.Account:type_name -> pb.Authentication.Form.AccountInfo
	9,  // 3: pb.Authentication.Form.Register.Account:type_name -> pb.Authentication.Form.RegisterAcount
	4,  // 4: pb.Authentication.Form.Register.SMS:type_name -> pb.Authentication.Form.MobilePhoneSMSCode
	10, // 5: pb.Authentication.Form.Register.CheckUsername:type_name -> pb.Authentication.Form.RegisterCheckUsername
	4,  // 6: pb.Authentication.Form.RegisterReply.SMS:type_name -> pb.Authentication.Form.MobilePhoneSMSCode
	2,  // 7: pb.Authentication.Form.RegisterReply.Account:type_name -> pb.Authentication.Form.AccountInfo
	11, // 8: pb.Authentication.Form.RegisterReply.CheckUsername:type_name -> pb.Authentication.Form.RegisterCheckUsernameReply
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kits_auth_proto_pb_auth_proto_init() }
func file_kits_auth_proto_pb_auth_proto_init() {
	if File_kits_auth_proto_pb_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kits_auth_proto_pb_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_LoginAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_MobilePhoneSMSCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_LoginRelpy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_RegisterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_RegisterAcount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_RegisterCheckUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_auth_proto_pb_auth_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication_Form_RegisterCheckUsernameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kits_auth_proto_pb_auth_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Authentication_Form_Login_Account)(nil),
		(*Authentication_Form_Login_SMS)(nil),
	}
	file_kits_auth_proto_pb_auth_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Authentication_Form_Register_Account)(nil),
		(*Authentication_Form_Register_SMS)(nil),
		(*Authentication_Form_Register_CheckUsername)(nil),
	}
	file_kits_auth_proto_pb_auth_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Authentication_Form_RegisterReply_SMS)(nil),
		(*Authentication_Form_RegisterReply_Account)(nil),
		(*Authentication_Form_RegisterReply_CheckUsername)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kits_auth_proto_pb_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kits_auth_proto_pb_auth_proto_goTypes,
		DependencyIndexes: file_kits_auth_proto_pb_auth_proto_depIdxs,
		MessageInfos:      file_kits_auth_proto_pb_auth_proto_msgTypes,
	}.Build()
	File_kits_auth_proto_pb_auth_proto = out.File
	file_kits_auth_proto_pb_auth_proto_rawDesc = nil
	file_kits_auth_proto_pb_auth_proto_goTypes = nil
	file_kits_auth_proto_pb_auth_proto_depIdxs = nil
}
