// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: kits/sfu/proto/pb/sfu.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SFU_Target int32

const (
	SFU_PUBLISHER  SFU_Target = 0
	SFU_SUBSCRIBER SFU_Target = 1
)

// Enum value maps for SFU_Target.
var (
	SFU_Target_name = map[int32]string{
		0: "PUBLISHER",
		1: "SUBSCRIBER",
	}
	SFU_Target_value = map[string]int32{
		"PUBLISHER":  0,
		"SUBSCRIBER": 1,
	}
)

func (x SFU_Target) Enum() *SFU_Target {
	p := new(SFU_Target)
	*p = x
	return p
}

func (x SFU_Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SFU_Target) Descriptor() protoreflect.EnumDescriptor {
	return file_kits_sfu_proto_pb_sfu_proto_enumTypes[0].Descriptor()
}

func (SFU_Target) Type() protoreflect.EnumType {
	return &file_kits_sfu_proto_pb_sfu_proto_enumTypes[0]
}

func (x SFU_Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SFU_Target.Descriptor instead.
func (SFU_Target) EnumDescriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 0}
}

type SFU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SFU) Reset() {
	*x = SFU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU) ProtoMessage() {}

func (x *SFU) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU.ProtoReflect.Descriptor instead.
func (*SFU) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0}
}

type SFU_Subscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SFU_Subscribe) Reset() {
	*x = SFU_Subscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Subscribe) ProtoMessage() {}

func (x *SFU_Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Subscribe.ProtoReflect.Descriptor instead.
func (*SFU_Subscribe) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 0}
}

type SFU_Trickle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target    SFU_Target `protobuf:"varint,1,opt,name=Target,proto3,enum=pb.SFU_Target" json:"Target,omitempty"`
	Candidate string     `protobuf:"bytes,2,opt,name=Candidate,proto3" json:"Candidate,omitempty"`
}

func (x *SFU_Trickle) Reset() {
	*x = SFU_Trickle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Trickle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Trickle) ProtoMessage() {}

func (x *SFU_Trickle) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Trickle.ProtoReflect.Descriptor instead.
func (*SFU_Trickle) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SFU_Trickle) GetTarget() SFU_Target {
	if x != nil {
		return x.Target
	}
	return SFU_PUBLISHER
}

func (x *SFU_Trickle) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type SFU_Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SFU_Signal) Reset() {
	*x = SFU_Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Signal) ProtoMessage() {}

func (x *SFU_Signal) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Signal.ProtoReflect.Descriptor instead.
func (*SFU_Signal) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 2}
}

type SFU_Subscribe_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	PeerId    string `protobuf:"bytes,2,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
}

func (x *SFU_Subscribe_Request) Reset() {
	*x = SFU_Subscribe_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Subscribe_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Subscribe_Request) ProtoMessage() {}

func (x *SFU_Subscribe_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Subscribe_Request.ProtoReflect.Descriptor instead.
func (*SFU_Subscribe_Request) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SFU_Subscribe_Request) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SFU_Subscribe_Request) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type SFU_Subscribe_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *SFU_Subscribe_Reply) Reset() {
	*x = SFU_Subscribe_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Subscribe_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Subscribe_Reply) ProtoMessage() {}

func (x *SFU_Subscribe_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Subscribe_Reply.ProtoReflect.Descriptor instead.
func (*SFU_Subscribe_Reply) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *SFU_Subscribe_Reply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SFU_Signal_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	// Types that are assignable to Payload:
	//	*SFU_Signal_Request_Description
	//	*SFU_Signal_Request_Trickle
	Payload isSFU_Signal_Request_Payload `protobuf_oneof:"Payload"`
}

func (x *SFU_Signal_Request) Reset() {
	*x = SFU_Signal_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Signal_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Signal_Request) ProtoMessage() {}

func (x *SFU_Signal_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Signal_Request.ProtoReflect.Descriptor instead.
func (*SFU_Signal_Request) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *SFU_Signal_Request) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (m *SFU_Signal_Request) GetPayload() isSFU_Signal_Request_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SFU_Signal_Request) GetDescription() []byte {
	if x, ok := x.GetPayload().(*SFU_Signal_Request_Description); ok {
		return x.Description
	}
	return nil
}

func (x *SFU_Signal_Request) GetTrickle() *SFU_Trickle {
	if x, ok := x.GetPayload().(*SFU_Signal_Request_Trickle); ok {
		return x.Trickle
	}
	return nil
}

type isSFU_Signal_Request_Payload interface {
	isSFU_Signal_Request_Payload()
}

type SFU_Signal_Request_Description struct {
	Description []byte `protobuf:"bytes,2,opt,name=Description,proto3,oneof"`
}

type SFU_Signal_Request_Trickle struct {
	Trickle *SFU_Trickle `protobuf:"bytes,3,opt,name=trickle,proto3,oneof"`
}

func (*SFU_Signal_Request_Description) isSFU_Signal_Request_Payload() {}

func (*SFU_Signal_Request_Trickle) isSFU_Signal_Request_Payload() {}

type SFU_Signal_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	PeerId    string `protobuf:"bytes,2,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
	// Types that are assignable to Payload:
	//	*SFU_Signal_Reply_Description
	//	*SFU_Signal_Reply_Trickle
	//	*SFU_Signal_Reply_IceConnectionState
	Payload isSFU_Signal_Reply_Payload `protobuf_oneof:"Payload"`
}

func (x *SFU_Signal_Reply) Reset() {
	*x = SFU_Signal_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFU_Signal_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFU_Signal_Reply) ProtoMessage() {}

func (x *SFU_Signal_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_sfu_proto_pb_sfu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFU_Signal_Reply.ProtoReflect.Descriptor instead.
func (*SFU_Signal_Reply) Descriptor() ([]byte, []int) {
	return file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *SFU_Signal_Reply) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SFU_Signal_Reply) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (m *SFU_Signal_Reply) GetPayload() isSFU_Signal_Reply_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SFU_Signal_Reply) GetDescription() []byte {
	if x, ok := x.GetPayload().(*SFU_Signal_Reply_Description); ok {
		return x.Description
	}
	return nil
}

func (x *SFU_Signal_Reply) GetTrickle() *SFU_Trickle {
	if x, ok := x.GetPayload().(*SFU_Signal_Reply_Trickle); ok {
		return x.Trickle
	}
	return nil
}

func (x *SFU_Signal_Reply) GetIceConnectionState() string {
	if x, ok := x.GetPayload().(*SFU_Signal_Reply_IceConnectionState); ok {
		return x.IceConnectionState
	}
	return ""
}

type isSFU_Signal_Reply_Payload interface {
	isSFU_Signal_Reply_Payload()
}

type SFU_Signal_Reply_Description struct {
	Description []byte `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
}

type SFU_Signal_Reply_Trickle struct {
	Trickle *SFU_Trickle `protobuf:"bytes,4,opt,name=trickle,proto3,oneof"`
}

type SFU_Signal_Reply_IceConnectionState struct {
	IceConnectionState string `protobuf:"bytes,5,opt,name=iceConnectionState,proto3,oneof"`
}

func (*SFU_Signal_Reply_Description) isSFU_Signal_Reply_Payload() {}

func (*SFU_Signal_Reply_Trickle) isSFU_Signal_Reply_Payload() {}

func (*SFU_Signal_Reply_IceConnectionState) isSFU_Signal_Reply_Payload() {}

var File_kits_sfu_proto_pb_sfu_proto protoreflect.FileDescriptor

var file_kits_sfu_proto_pb_sfu_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x73, 0x66, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x66, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0xc5, 0x04, 0x0a, 0x03, 0x53, 0x46, 0x55, 0x1a, 0x65, 0x0a, 0x09, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x1a, 0x3f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x17, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b,
	0x1a, 0x4f, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x46, 0x55, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x1a, 0xdc, 0x02, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x1a, 0x83, 0x01, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x74, 0x72,
	0x69, 0x63, 0x6b, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x46, 0x55, 0x2e, 0x54, 0x72, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x74, 0x72, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x1a, 0xcb, 0x01, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x63, 0x6b, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x46, 0x55,
	0x2e, 0x54, 0x72, 0x69, 0x63, 0x6b, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x07, 0x74, 0x72, 0x69, 0x63,
	0x6b, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x12, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x12, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x27, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x53, 0x48, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x42,
	0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x52, 0x10, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x6f,
	0x2f, 0x62, 0x61, 0x61, 0x2f, 0x6b, 0x69, 0x74, 0x2f, 0x73, 0x66, 0x75, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kits_sfu_proto_pb_sfu_proto_rawDescOnce sync.Once
	file_kits_sfu_proto_pb_sfu_proto_rawDescData = file_kits_sfu_proto_pb_sfu_proto_rawDesc
)

func file_kits_sfu_proto_pb_sfu_proto_rawDescGZIP() []byte {
	file_kits_sfu_proto_pb_sfu_proto_rawDescOnce.Do(func() {
		file_kits_sfu_proto_pb_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(file_kits_sfu_proto_pb_sfu_proto_rawDescData)
	})
	return file_kits_sfu_proto_pb_sfu_proto_rawDescData
}

var file_kits_sfu_proto_pb_sfu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kits_sfu_proto_pb_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kits_sfu_proto_pb_sfu_proto_goTypes = []interface{}{
	(SFU_Target)(0),               // 0: pb.SFU.Target
	(*SFU)(nil),                   // 1: pb.SFU
	(*SFU_Subscribe)(nil),         // 2: pb.SFU.Subscribe
	(*SFU_Trickle)(nil),           // 3: pb.SFU.Trickle
	(*SFU_Signal)(nil),            // 4: pb.SFU.Signal
	(*SFU_Subscribe_Request)(nil), // 5: pb.SFU.Subscribe.Request
	(*SFU_Subscribe_Reply)(nil),   // 6: pb.SFU.Subscribe.Reply
	(*SFU_Signal_Request)(nil),    // 7: pb.SFU.Signal.Request
	(*SFU_Signal_Reply)(nil),      // 8: pb.SFU.Signal.Reply
}
var file_kits_sfu_proto_pb_sfu_proto_depIdxs = []int32{
	0, // 0: pb.SFU.Trickle.Target:type_name -> pb.SFU.Target
	3, // 1: pb.SFU.Signal.Request.trickle:type_name -> pb.SFU.Trickle
	3, // 2: pb.SFU.Signal.Reply.trickle:type_name -> pb.SFU.Trickle
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kits_sfu_proto_pb_sfu_proto_init() }
func file_kits_sfu_proto_pb_sfu_proto_init() {
	if File_kits_sfu_proto_pb_sfu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Subscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Trickle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Subscribe_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Subscribe_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Signal_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_sfu_proto_pb_sfu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFU_Signal_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kits_sfu_proto_pb_sfu_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*SFU_Signal_Request_Description)(nil),
		(*SFU_Signal_Request_Trickle)(nil),
	}
	file_kits_sfu_proto_pb_sfu_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*SFU_Signal_Reply_Description)(nil),
		(*SFU_Signal_Reply_Trickle)(nil),
		(*SFU_Signal_Reply_IceConnectionState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kits_sfu_proto_pb_sfu_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kits_sfu_proto_pb_sfu_proto_goTypes,
		DependencyIndexes: file_kits_sfu_proto_pb_sfu_proto_depIdxs,
		EnumInfos:         file_kits_sfu_proto_pb_sfu_proto_enumTypes,
		MessageInfos:      file_kits_sfu_proto_pb_sfu_proto_msgTypes,
	}.Build()
	File_kits_sfu_proto_pb_sfu_proto = out.File
	file_kits_sfu_proto_pb_sfu_proto_rawDesc = nil
	file_kits_sfu_proto_pb_sfu_proto_goTypes = nil
	file_kits_sfu_proto_pb_sfu_proto_depIdxs = nil
}
