// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: kits/imf/proto/pb/imf.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IMF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMF) Reset() {
	*x = IMF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF) ProtoMessage() {}

func (x *IMF) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF.ProtoReflect.Descriptor instead.
func (*IMF) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0}
}

type IMF_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*IMF_Request_Text
	//	*IMF_Request_Video
	//	*IMF_Request_Image
	//	*IMF_Request_Voice
	//	*IMF_Request_File
	Payload       isIMF_Request_Payload `protobuf_oneof:"Payload"`
	MsgId         uint64                `protobuf:"varint,6,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Topic         string                `protobuf:"bytes,7,opt,name=Topic,proto3" json:"Topic,omitempty"`
	ToType        int32                 `protobuf:"varint,8,opt,name=ToType,proto3" json:"ToType,omitempty"`
	RequiredReply bool                  `protobuf:"varint,9,opt,name=RequiredReply,proto3" json:"RequiredReply,omitempty"` // 是否必须回复。不管对错都要回复 否则，只有当消息不有问题时才回复
	SeqId         uint64                `protobuf:"varint,10,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
}

func (x *IMF_Request) Reset() {
	*x = IMF_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Request) ProtoMessage() {}

func (x *IMF_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Request.ProtoReflect.Descriptor instead.
func (*IMF_Request) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 0}
}

func (m *IMF_Request) GetPayload() isIMF_Request_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *IMF_Request) GetText() *IMF_Content_Text {
	if x, ok := x.GetPayload().(*IMF_Request_Text); ok {
		return x.Text
	}
	return nil
}

func (x *IMF_Request) GetVideo() *IMF_Content_Video {
	if x, ok := x.GetPayload().(*IMF_Request_Video); ok {
		return x.Video
	}
	return nil
}

func (x *IMF_Request) GetImage() *IMF_Content_Image {
	if x, ok := x.GetPayload().(*IMF_Request_Image); ok {
		return x.Image
	}
	return nil
}

func (x *IMF_Request) GetVoice() *IMF_Content_Voice {
	if x, ok := x.GetPayload().(*IMF_Request_Voice); ok {
		return x.Voice
	}
	return nil
}

func (x *IMF_Request) GetFile() *IMF_Content_File {
	if x, ok := x.GetPayload().(*IMF_Request_File); ok {
		return x.File
	}
	return nil
}

func (x *IMF_Request) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *IMF_Request) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *IMF_Request) GetToType() int32 {
	if x != nil {
		return x.ToType
	}
	return 0
}

func (x *IMF_Request) GetRequiredReply() bool {
	if x != nil {
		return x.RequiredReply
	}
	return false
}

func (x *IMF_Request) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type isIMF_Request_Payload interface {
	isIMF_Request_Payload()
}

type IMF_Request_Text struct {
	Text *IMF_Content_Text `protobuf:"bytes,1,opt,name=Text,proto3,oneof"`
}

type IMF_Request_Video struct {
	Video *IMF_Content_Video `protobuf:"bytes,2,opt,name=Video,proto3,oneof"`
}

type IMF_Request_Image struct {
	Image *IMF_Content_Image `protobuf:"bytes,3,opt,name=Image,proto3,oneof"`
}

type IMF_Request_Voice struct {
	Voice *IMF_Content_Voice `protobuf:"bytes,4,opt,name=Voice,proto3,oneof"`
}

type IMF_Request_File struct {
	File *IMF_Content_File `protobuf:"bytes,5,opt,name=File,proto3,oneof"`
}

func (*IMF_Request_Text) isIMF_Request_Payload() {}

func (*IMF_Request_Video) isIMF_Request_Payload() {}

func (*IMF_Request_Image) isIMF_Request_Payload() {}

func (*IMF_Request_Voice) isIMF_Request_Payload() {}

func (*IMF_Request_File) isIMF_Request_Payload() {}

type IMF_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	// Types that are assignable to Payload:
	//	*IMF_Reply_Text
	//	*IMF_Reply_Video
	//	*IMF_Reply_Image
	//	*IMF_Reply_Voice
	//	*IMF_Reply_File
	Payload isIMF_Reply_Payload `protobuf_oneof:"Payload"`
	MsgId   uint64              `protobuf:"varint,7,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Topic   string              `protobuf:"bytes,8,opt,name=Topic,proto3" json:"Topic,omitempty"`
	ToType  int32               `protobuf:"varint,9,opt,name=ToType,proto3" json:"ToType,omitempty"`
	SeqId   uint64              `protobuf:"varint,10,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
}

func (x *IMF_Reply) Reset() {
	*x = IMF_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Reply) ProtoMessage() {}

func (x *IMF_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Reply.ProtoReflect.Descriptor instead.
func (*IMF_Reply) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IMF_Reply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

func (m *IMF_Reply) GetPayload() isIMF_Reply_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *IMF_Reply) GetText() *IMF_Content_Text {
	if x, ok := x.GetPayload().(*IMF_Reply_Text); ok {
		return x.Text
	}
	return nil
}

func (x *IMF_Reply) GetVideo() *IMF_Content_Video {
	if x, ok := x.GetPayload().(*IMF_Reply_Video); ok {
		return x.Video
	}
	return nil
}

func (x *IMF_Reply) GetImage() *IMF_Content_Image {
	if x, ok := x.GetPayload().(*IMF_Reply_Image); ok {
		return x.Image
	}
	return nil
}

func (x *IMF_Reply) GetVoice() *IMF_Content_Voice {
	if x, ok := x.GetPayload().(*IMF_Reply_Voice); ok {
		return x.Voice
	}
	return nil
}

func (x *IMF_Reply) GetFile() *IMF_Content_File {
	if x, ok := x.GetPayload().(*IMF_Reply_File); ok {
		return x.File
	}
	return nil
}

func (x *IMF_Reply) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *IMF_Reply) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *IMF_Reply) GetToType() int32 {
	if x != nil {
		return x.ToType
	}
	return 0
}

func (x *IMF_Reply) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type isIMF_Reply_Payload interface {
	isIMF_Reply_Payload()
}

type IMF_Reply_Text struct {
	Text *IMF_Content_Text `protobuf:"bytes,2,opt,name=Text,proto3,oneof"`
}

type IMF_Reply_Video struct {
	Video *IMF_Content_Video `protobuf:"bytes,3,opt,name=Video,proto3,oneof"`
}

type IMF_Reply_Image struct {
	Image *IMF_Content_Image `protobuf:"bytes,4,opt,name=Image,proto3,oneof"`
}

type IMF_Reply_Voice struct {
	Voice *IMF_Content_Voice `protobuf:"bytes,5,opt,name=Voice,proto3,oneof"`
}

type IMF_Reply_File struct {
	File *IMF_Content_File `protobuf:"bytes,6,opt,name=File,proto3,oneof"`
}

func (*IMF_Reply_Text) isIMF_Reply_Payload() {}

func (*IMF_Reply_Video) isIMF_Reply_Payload() {}

func (*IMF_Reply_Image) isIMF_Reply_Payload() {}

func (*IMF_Reply_Voice) isIMF_Reply_Payload() {}

func (*IMF_Reply_File) isIMF_Reply_Payload() {}

type IMF_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMF_Content) Reset() {
	*x = IMF_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content) ProtoMessage() {}

func (x *IMF_Content) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content.ProtoReflect.Descriptor instead.
func (*IMF_Content) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2}
}

type IMF_DirtyWords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMF_DirtyWords) Reset() {
	*x = IMF_DirtyWords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_DirtyWords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_DirtyWords) ProtoMessage() {}

func (x *IMF_DirtyWords) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_DirtyWords.ProtoReflect.Descriptor instead.
func (*IMF_DirtyWords) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 3}
}

type IMF_Content_Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *IMF_Content_Text) Reset() {
	*x = IMF_Content_Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content_Text) ProtoMessage() {}

func (x *IMF_Content_Text) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content_Text.ProtoReflect.Descriptor instead.
func (*IMF_Content_Text) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *IMF_Content_Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IMF_Content_Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`     //
	Name int32  `protobuf:"varint,2,opt,name=Name,proto3" json:"Name,omitempty"` // 名称
	Url  string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *IMF_Content_Video) Reset() {
	*x = IMF_Content_Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content_Video) ProtoMessage() {}

func (x *IMF_Content_Video) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content_Video.ProtoReflect.Descriptor instead.
func (*IMF_Content_Video) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *IMF_Content_Video) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *IMF_Content_Video) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *IMF_Content_Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type IMF_Content_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`          //
	Content []byte `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"` // 缩略图
	Name    int32  `protobuf:"varint,3,opt,name=Name,proto3" json:"Name,omitempty"`      // 名称
	Url     string `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *IMF_Content_Image) Reset() {
	*x = IMF_Content_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content_Image) ProtoMessage() {}

func (x *IMF_Content_Image) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content_Image.ProtoReflect.Descriptor instead.
func (*IMF_Content_Image) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2, 2}
}

func (x *IMF_Content_Image) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *IMF_Content_Image) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IMF_Content_Image) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *IMF_Content_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type IMF_Content_Voice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *IMF_Content_Voice) Reset() {
	*x = IMF_Content_Voice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content_Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content_Voice) ProtoMessage() {}

func (x *IMF_Content_Voice) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content_Voice.ProtoReflect.Descriptor instead.
func (*IMF_Content_Voice) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2, 3}
}

func (x *IMF_Content_Voice) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type IMF_Content_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"` //
	Url   string `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	Types string `protobuf:"bytes,3,opt,name=Types,proto3" json:"Types,omitempty"` //
	Name  int32  `protobuf:"varint,4,opt,name=Name,proto3" json:"Name,omitempty"`  // 图大小
}

func (x *IMF_Content_File) Reset() {
	*x = IMF_Content_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content_File) ProtoMessage() {}

func (x *IMF_Content_File) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content_File.ProtoReflect.Descriptor instead.
func (*IMF_Content_File) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2, 4}
}

func (x *IMF_Content_File) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *IMF_Content_File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IMF_Content_File) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *IMF_Content_File) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type IMF_DirtyWords_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*IMF_DirtyWords_Request_Add
	//	*IMF_DirtyWords_Request_Delete
	Payload isIMF_DirtyWords_Request_Payload `protobuf_oneof:"Payload"`
}

func (x *IMF_DirtyWords_Request) Reset() {
	*x = IMF_DirtyWords_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_DirtyWords_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_DirtyWords_Request) ProtoMessage() {}

func (x *IMF_DirtyWords_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_DirtyWords_Request.ProtoReflect.Descriptor instead.
func (*IMF_DirtyWords_Request) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (m *IMF_DirtyWords_Request) GetPayload() isIMF_DirtyWords_Request_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *IMF_DirtyWords_Request) GetAdd() string {
	if x, ok := x.GetPayload().(*IMF_DirtyWords_Request_Add); ok {
		return x.Add
	}
	return ""
}

func (x *IMF_DirtyWords_Request) GetDelete() string {
	if x, ok := x.GetPayload().(*IMF_DirtyWords_Request_Delete); ok {
		return x.Delete
	}
	return ""
}

type isIMF_DirtyWords_Request_Payload interface {
	isIMF_DirtyWords_Request_Payload()
}

type IMF_DirtyWords_Request_Add struct {
	Add string `protobuf:"bytes,1,opt,name=Add,proto3,oneof"`
}

type IMF_DirtyWords_Request_Delete struct {
	Delete string `protobuf:"bytes,2,opt,name=Delete,proto3,oneof"`
}

func (*IMF_DirtyWords_Request_Add) isIMF_DirtyWords_Request_Payload() {}

func (*IMF_DirtyWords_Request_Delete) isIMF_DirtyWords_Request_Payload() {}

type IMF_DirtyWords_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *IMF_DirtyWords_Reply) Reset() {
	*x = IMF_DirtyWords_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_DirtyWords_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_DirtyWords_Reply) ProtoMessage() {}

func (x *IMF_DirtyWords_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_DirtyWords_Reply.ProtoReflect.Descriptor instead.
func (*IMF_DirtyWords_Reply) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *IMF_DirtyWords_Reply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

var File_kits_imf_proto_pb_imf_proto protoreflect.FileDescriptor

var file_kits_imf_proto_pb_imf_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x69, 0x6d, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x2f, 0x69, 0x6d, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x8d, 0x09, 0x0a, 0x03, 0x49, 0x4d, 0x46, 0x1a, 0xf9, 0x02, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x2d, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x12, 0x2d, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x2d, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x71, 0x49, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x65, 0x71, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0xe1, 0x02, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b, 0x12,
	0x2a, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x54,
	0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x48, 0x00, 0x52, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x2d, 0x0a, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x56, 0x6f, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d,
	0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x48,
	0x00, 0x52, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x71, 0x49,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x65, 0x71, 0x49, 0x64, 0x42, 0x09,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0xba, 0x02, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x20, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x3d, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x1a, 0x57, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x1a,
	0x21, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x1a, 0x52, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x69, 0x0a, 0x0a, 0x44, 0x69, 0x72, 0x74, 0x79, 0x57,
	0x6f, 0x72, 0x64, 0x73, 0x1a, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03,
	0x41, 0x64, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x17, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f,
	0x4b, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x61, 0x61, 0x2f, 0x6b, 0x69, 0x74,
	0x73, 0x2f, 0x69, 0x6d, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kits_imf_proto_pb_imf_proto_rawDescOnce sync.Once
	file_kits_imf_proto_pb_imf_proto_rawDescData = file_kits_imf_proto_pb_imf_proto_rawDesc
)

func file_kits_imf_proto_pb_imf_proto_rawDescGZIP() []byte {
	file_kits_imf_proto_pb_imf_proto_rawDescOnce.Do(func() {
		file_kits_imf_proto_pb_imf_proto_rawDescData = protoimpl.X.CompressGZIP(file_kits_imf_proto_pb_imf_proto_rawDescData)
	})
	return file_kits_imf_proto_pb_imf_proto_rawDescData
}

var file_kits_imf_proto_pb_imf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kits_imf_proto_pb_imf_proto_goTypes = []interface{}{
	(*IMF)(nil),                    // 0: pb.IMF
	(*IMF_Request)(nil),            // 1: pb.IMF.Request
	(*IMF_Reply)(nil),              // 2: pb.IMF.Reply
	(*IMF_Content)(nil),            // 3: pb.IMF.Content
	(*IMF_DirtyWords)(nil),         // 4: pb.IMF.DirtyWords
	(*IMF_Content_Text)(nil),       // 5: pb.IMF.Content.Text
	(*IMF_Content_Video)(nil),      // 6: pb.IMF.Content.Video
	(*IMF_Content_Image)(nil),      // 7: pb.IMF.Content.Image
	(*IMF_Content_Voice)(nil),      // 8: pb.IMF.Content.Voice
	(*IMF_Content_File)(nil),       // 9: pb.IMF.Content.File
	(*IMF_DirtyWords_Request)(nil), // 10: pb.IMF.DirtyWords.Request
	(*IMF_DirtyWords_Reply)(nil),   // 11: pb.IMF.DirtyWords.Reply
}
var file_kits_imf_proto_pb_imf_proto_depIdxs = []int32{
	5,  // 0: pb.IMF.Request.Text:type_name -> pb.IMF.Content.Text
	6,  // 1: pb.IMF.Request.Video:type_name -> pb.IMF.Content.Video
	7,  // 2: pb.IMF.Request.Image:type_name -> pb.IMF.Content.Image
	8,  // 3: pb.IMF.Request.Voice:type_name -> pb.IMF.Content.Voice
	9,  // 4: pb.IMF.Request.File:type_name -> pb.IMF.Content.File
	5,  // 5: pb.IMF.Reply.Text:type_name -> pb.IMF.Content.Text
	6,  // 6: pb.IMF.Reply.Video:type_name -> pb.IMF.Content.Video
	7,  // 7: pb.IMF.Reply.Image:type_name -> pb.IMF.Content.Image
	8,  // 8: pb.IMF.Reply.Voice:type_name -> pb.IMF.Content.Voice
	9,  // 9: pb.IMF.Reply.File:type_name -> pb.IMF.Content.File
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_kits_imf_proto_pb_imf_proto_init() }
func file_kits_imf_proto_pb_imf_proto_init() {
	if File_kits_imf_proto_pb_imf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kits_imf_proto_pb_imf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_DirtyWords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content_Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content_Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content_Voice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_DirtyWords_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_DirtyWords_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kits_imf_proto_pb_imf_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*IMF_Request_Text)(nil),
		(*IMF_Request_Video)(nil),
		(*IMF_Request_Image)(nil),
		(*IMF_Request_Voice)(nil),
		(*IMF_Request_File)(nil),
	}
	file_kits_imf_proto_pb_imf_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*IMF_Reply_Text)(nil),
		(*IMF_Reply_Video)(nil),
		(*IMF_Reply_Image)(nil),
		(*IMF_Reply_Voice)(nil),
		(*IMF_Reply_File)(nil),
	}
	file_kits_imf_proto_pb_imf_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*IMF_DirtyWords_Request_Add)(nil),
		(*IMF_DirtyWords_Request_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kits_imf_proto_pb_imf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kits_imf_proto_pb_imf_proto_goTypes,
		DependencyIndexes: file_kits_imf_proto_pb_imf_proto_depIdxs,
		MessageInfos:      file_kits_imf_proto_pb_imf_proto_msgTypes,
	}.Build()
	File_kits_imf_proto_pb_imf_proto = out.File
	file_kits_imf_proto_pb_imf_proto_rawDesc = nil
	file_kits_imf_proto_pb_imf_proto_goTypes = nil
	file_kits_imf_proto_pb_imf_proto_depIdxs = nil
}
