// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: kits/imf/proto/pb/imf.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IMF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMF) Reset() {
	*x = IMF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF) ProtoMessage() {}

func (x *IMF) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF.ProtoReflect.Descriptor instead.
func (*IMF) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0}
}

type IMF_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*IMF_Content `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *IMF_Request) Reset() {
	*x = IMF_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Request) ProtoMessage() {}

func (x *IMF_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Request.ProtoReflect.Descriptor instead.
func (*IMF_Request) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IMF_Request) GetValues() []*IMF_Content {
	if x != nil {
		return x.Values
	}
	return nil
}

type IMF_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool         `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Content *IMF_Content `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *IMF_Response) Reset() {
	*x = IMF_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Response) ProtoMessage() {}

func (x *IMF_Response) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Response.ProtoReflect.Descriptor instead.
func (*IMF_Response) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IMF_Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IMF_Response) GetContent() *IMF_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type IMF_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*IMF_Response `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *IMF_Reply) Reset() {
	*x = IMF_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Reply) ProtoMessage() {}

func (x *IMF_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Reply.ProtoReflect.Descriptor instead.
func (*IMF_Reply) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 2}
}

func (x *IMF_Reply) GetValues() []*IMF_Response {
	if x != nil {
		return x.Values
	}
	return nil
}

type IMF_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId       uint64   `protobuf:"varint,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	SeqId       []uint64 `protobuf:"varint,2,rep,packed,name=SeqId,proto3" json:"SeqId,omitempty"`
	Topic       string   `protobuf:"bytes,3,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Group       int32    `protobuf:"varint,4,opt,name=Group,proto3" json:"Group,omitempty"`
	Content     string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	To          uint64   `protobuf:"varint,6,opt,name=To,proto3" json:"To,omitempty"`
	From        uint64   `protobuf:"varint,7,opt,name=From,proto3" json:"From,omitempty"`
	ContentType string   `protobuf:"bytes,9,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
}

func (x *IMF_Content) Reset() {
	*x = IMF_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_Content) ProtoMessage() {}

func (x *IMF_Content) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_Content.ProtoReflect.Descriptor instead.
func (*IMF_Content) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 3}
}

func (x *IMF_Content) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *IMF_Content) GetSeqId() []uint64 {
	if x != nil {
		return x.SeqId
	}
	return nil
}

func (x *IMF_Content) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *IMF_Content) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *IMF_Content) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IMF_Content) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *IMF_Content) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *IMF_Content) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type IMF_DirtyWords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IMF_DirtyWords) Reset() {
	*x = IMF_DirtyWords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_DirtyWords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_DirtyWords) ProtoMessage() {}

func (x *IMF_DirtyWords) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_DirtyWords.ProtoReflect.Descriptor instead.
func (*IMF_DirtyWords) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 4}
}

type IMF_DirtyWords_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*IMF_DirtyWords_Request_Add
	//	*IMF_DirtyWords_Request_Delete
	Payload isIMF_DirtyWords_Request_Payload `protobuf_oneof:"Payload"`
}

func (x *IMF_DirtyWords_Request) Reset() {
	*x = IMF_DirtyWords_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_DirtyWords_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_DirtyWords_Request) ProtoMessage() {}

func (x *IMF_DirtyWords_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_DirtyWords_Request.ProtoReflect.Descriptor instead.
func (*IMF_DirtyWords_Request) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (m *IMF_DirtyWords_Request) GetPayload() isIMF_DirtyWords_Request_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *IMF_DirtyWords_Request) GetAdd() string {
	if x, ok := x.GetPayload().(*IMF_DirtyWords_Request_Add); ok {
		return x.Add
	}
	return ""
}

func (x *IMF_DirtyWords_Request) GetDelete() string {
	if x, ok := x.GetPayload().(*IMF_DirtyWords_Request_Delete); ok {
		return x.Delete
	}
	return ""
}

type isIMF_DirtyWords_Request_Payload interface {
	isIMF_DirtyWords_Request_Payload()
}

type IMF_DirtyWords_Request_Add struct {
	Add string `protobuf:"bytes,1,opt,name=Add,proto3,oneof"`
}

type IMF_DirtyWords_Request_Delete struct {
	Delete string `protobuf:"bytes,2,opt,name=Delete,proto3,oneof"`
}

func (*IMF_DirtyWords_Request_Add) isIMF_DirtyWords_Request_Payload() {}

func (*IMF_DirtyWords_Request_Delete) isIMF_DirtyWords_Request_Payload() {}

type IMF_DirtyWords_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *IMF_DirtyWords_Reply) Reset() {
	*x = IMF_DirtyWords_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMF_DirtyWords_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMF_DirtyWords_Reply) ProtoMessage() {}

func (x *IMF_DirtyWords_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_imf_proto_pb_imf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMF_DirtyWords_Reply.ProtoReflect.Descriptor instead.
func (*IMF_DirtyWords_Reply) Descriptor() ([]byte, []int) {
	return file_kits_imf_proto_pb_imf_proto_rawDescGZIP(), []int{0, 4, 1}
}

func (x *IMF_DirtyWords_Reply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

var File_kits_imf_proto_pb_imf_proto protoreflect.FileDescriptor

var file_kits_imf_proto_pb_imf_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x69, 0x6d, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x2f, 0x69, 0x6d, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0xe2, 0x03, 0x0a, 0x03, 0x49, 0x4d, 0x46, 0x1a, 0x32, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x45, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x29, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x4d, 0x46, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x1a, 0x31, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a,
	0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x4d, 0x46, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0xc1, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x71,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x53, 0x65, 0x71, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x69, 0x0a, 0x0a, 0x44,
	0x69, 0x72, 0x74, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x03, 0x41, 0x64, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x17, 0x0a,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x61,
	0x61, 0x2f, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x69, 0x6d, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kits_imf_proto_pb_imf_proto_rawDescOnce sync.Once
	file_kits_imf_proto_pb_imf_proto_rawDescData = file_kits_imf_proto_pb_imf_proto_rawDesc
)

func file_kits_imf_proto_pb_imf_proto_rawDescGZIP() []byte {
	file_kits_imf_proto_pb_imf_proto_rawDescOnce.Do(func() {
		file_kits_imf_proto_pb_imf_proto_rawDescData = protoimpl.X.CompressGZIP(file_kits_imf_proto_pb_imf_proto_rawDescData)
	})
	return file_kits_imf_proto_pb_imf_proto_rawDescData
}

var file_kits_imf_proto_pb_imf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kits_imf_proto_pb_imf_proto_goTypes = []interface{}{
	(*IMF)(nil),                    // 0: pb.IMF
	(*IMF_Request)(nil),            // 1: pb.IMF.Request
	(*IMF_Response)(nil),           // 2: pb.IMF.Response
	(*IMF_Reply)(nil),              // 3: pb.IMF.Reply
	(*IMF_Content)(nil),            // 4: pb.IMF.Content
	(*IMF_DirtyWords)(nil),         // 5: pb.IMF.DirtyWords
	(*IMF_DirtyWords_Request)(nil), // 6: pb.IMF.DirtyWords.Request
	(*IMF_DirtyWords_Reply)(nil),   // 7: pb.IMF.DirtyWords.Reply
}
var file_kits_imf_proto_pb_imf_proto_depIdxs = []int32{
	4, // 0: pb.IMF.Request.Values:type_name -> pb.IMF.Content
	4, // 1: pb.IMF.Response.Content:type_name -> pb.IMF.Content
	2, // 2: pb.IMF.Reply.Values:type_name -> pb.IMF.Response
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kits_imf_proto_pb_imf_proto_init() }
func file_kits_imf_proto_pb_imf_proto_init() {
	if File_kits_imf_proto_pb_imf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kits_imf_proto_pb_imf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_DirtyWords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_DirtyWords_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_imf_proto_pb_imf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMF_DirtyWords_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kits_imf_proto_pb_imf_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*IMF_DirtyWords_Request_Add)(nil),
		(*IMF_DirtyWords_Request_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kits_imf_proto_pb_imf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kits_imf_proto_pb_imf_proto_goTypes,
		DependencyIndexes: file_kits_imf_proto_pb_imf_proto_depIdxs,
		MessageInfos:      file_kits_imf_proto_pb_imf_proto_msgTypes,
	}.Build()
	File_kits_imf_proto_pb_imf_proto = out.File
	file_kits_imf_proto_pb_imf_proto_rawDesc = nil
	file_kits_imf_proto_pb_imf_proto_goTypes = nil
	file_kits_imf_proto_pb_imf_proto_depIdxs = nil
}
