// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: kits/im/proto/pb/im.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IM_Msg_ToTypes int32

const (
	IM_Msg_ToC IM_Msg_ToTypes = 0
	IM_Msg_ToG IM_Msg_ToTypes = 1
)

// Enum value maps for IM_Msg_ToTypes.
var (
	IM_Msg_ToTypes_name = map[int32]string{
		0: "ToC",
		1: "ToG",
	}
	IM_Msg_ToTypes_value = map[string]int32{
		"ToC": 0,
		"ToG": 1,
	}
)

func (x IM_Msg_ToTypes) Enum() *IM_Msg_ToTypes {
	p := new(IM_Msg_ToTypes)
	*p = x
	return p
}

func (x IM_Msg_ToTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IM_Msg_ToTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_kits_im_proto_pb_im_proto_enumTypes[0].Descriptor()
}

func (IM_Msg_ToTypes) Type() protoreflect.EnumType {
	return &file_kits_im_proto_pb_im_proto_enumTypes[0]
}

func (x IM_Msg_ToTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IM_Msg_ToTypes.Descriptor instead.
func (IM_Msg_ToTypes) EnumDescriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 0}
}

type IM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IM) Reset() {
	*x = IM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM) ProtoMessage() {}

func (x *IM) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM.ProtoReflect.Descriptor instead.
func (*IM) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0}
}

type IM_Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IM_Msg) Reset() {
	*x = IM_Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg) ProtoMessage() {}

func (x *IM_Msg) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg.ProtoReflect.Descriptor instead.
func (*IM_Msg) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0}
}

type IM_Msg_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId uint64 `protobuf:"varint,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	SeqID uint64 `protobuf:"varint,2,opt,name=SeqID,proto3" json:"SeqID,omitempty"`
	To    string `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	// Types that are assignable to Payload:
	//	*IM_Msg_Body_Text
	//	*IM_Msg_Body_Video
	//	*IM_Msg_Body_Image
	//	*IM_Msg_Body_Voice
	//	*IM_Msg_Body_File
	//	*IM_Msg_Body_Emoticon
	Payload     isIM_Msg_Body_Payload `protobuf_oneof:"Payload"`
	From        string                `protobuf:"bytes,10,opt,name=From,proto3" json:"From,omitempty"`
	FName       string                `protobuf:"bytes,11,opt,name=FName,proto3" json:"FName,omitempty"`
	FHeadImgurl string                `protobuf:"bytes,12,opt,name=FHeadImgurl,proto3" json:"FHeadImgurl,omitempty"`
	FSex        string                `protobuf:"bytes,13,opt,name=FSex,proto3" json:"FSex,omitempty"`
	ToType      IM_Msg_ToTypes        `protobuf:"varint,14,opt,name=ToType,proto3,enum=pb.IM_Msg_ToTypes" json:"ToType,omitempty"`
}

func (x *IM_Msg_Body) Reset() {
	*x = IM_Msg_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Body) ProtoMessage() {}

func (x *IM_Msg_Body) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Body.ProtoReflect.Descriptor instead.
func (*IM_Msg_Body) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *IM_Msg_Body) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *IM_Msg_Body) GetSeqID() uint64 {
	if x != nil {
		return x.SeqID
	}
	return 0
}

func (x *IM_Msg_Body) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (m *IM_Msg_Body) GetPayload() isIM_Msg_Body_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *IM_Msg_Body) GetText() *IM_Msg_Content_Text {
	if x, ok := x.GetPayload().(*IM_Msg_Body_Text); ok {
		return x.Text
	}
	return nil
}

func (x *IM_Msg_Body) GetVideo() *IM_Msg_Content_Video {
	if x, ok := x.GetPayload().(*IM_Msg_Body_Video); ok {
		return x.Video
	}
	return nil
}

func (x *IM_Msg_Body) GetImage() *IM_Msg_Content_Image {
	if x, ok := x.GetPayload().(*IM_Msg_Body_Image); ok {
		return x.Image
	}
	return nil
}

func (x *IM_Msg_Body) GetVoice() *IM_Msg_Content_Voice {
	if x, ok := x.GetPayload().(*IM_Msg_Body_Voice); ok {
		return x.Voice
	}
	return nil
}

func (x *IM_Msg_Body) GetFile() *IM_Msg_Content_File {
	if x, ok := x.GetPayload().(*IM_Msg_Body_File); ok {
		return x.File
	}
	return nil
}

func (x *IM_Msg_Body) GetEmoticon() *IM_Msg_Content_Emoticon {
	if x, ok := x.GetPayload().(*IM_Msg_Body_Emoticon); ok {
		return x.Emoticon
	}
	return nil
}

func (x *IM_Msg_Body) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *IM_Msg_Body) GetFName() string {
	if x != nil {
		return x.FName
	}
	return ""
}

func (x *IM_Msg_Body) GetFHeadImgurl() string {
	if x != nil {
		return x.FHeadImgurl
	}
	return ""
}

func (x *IM_Msg_Body) GetFSex() string {
	if x != nil {
		return x.FSex
	}
	return ""
}

func (x *IM_Msg_Body) GetToType() IM_Msg_ToTypes {
	if x != nil {
		return x.ToType
	}
	return IM_Msg_ToC
}

type isIM_Msg_Body_Payload interface {
	isIM_Msg_Body_Payload()
}

type IM_Msg_Body_Text struct {
	Text *IM_Msg_Content_Text `protobuf:"bytes,4,opt,name=Text,proto3,oneof"`
}

type IM_Msg_Body_Video struct {
	Video *IM_Msg_Content_Video `protobuf:"bytes,5,opt,name=Video,proto3,oneof"`
}

type IM_Msg_Body_Image struct {
	Image *IM_Msg_Content_Image `protobuf:"bytes,6,opt,name=Image,proto3,oneof"`
}

type IM_Msg_Body_Voice struct {
	Voice *IM_Msg_Content_Voice `protobuf:"bytes,7,opt,name=Voice,proto3,oneof"`
}

type IM_Msg_Body_File struct {
	File *IM_Msg_Content_File `protobuf:"bytes,8,opt,name=File,proto3,oneof"`
}

type IM_Msg_Body_Emoticon struct {
	Emoticon *IM_Msg_Content_Emoticon `protobuf:"bytes,9,opt,name=Emoticon,proto3,oneof"`
}

func (*IM_Msg_Body_Text) isIM_Msg_Body_Payload() {}

func (*IM_Msg_Body_Video) isIM_Msg_Body_Payload() {}

func (*IM_Msg_Body_Image) isIM_Msg_Body_Payload() {}

func (*IM_Msg_Body_Voice) isIM_Msg_Body_Payload() {}

func (*IM_Msg_Body_File) isIM_Msg_Body_Payload() {}

func (*IM_Msg_Body_Emoticon) isIM_Msg_Body_Payload() {}

type IM_Msg_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IM_Msg_Content) Reset() {
	*x = IM_Msg_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content) ProtoMessage() {}

func (x *IM_Msg_Content) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1}
}

type IM_Msg_Content_Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *IM_Msg_Content_Text) Reset() {
	*x = IM_Msg_Content_Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content_Text) ProtoMessage() {}

func (x *IM_Msg_Content_Text) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content_Text.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content_Text) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1, 0}
}

func (x *IM_Msg_Content_Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IM_Msg_Content_Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`          //
	Size    int32  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`      // 图大小
	Content []byte `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"` // 缩略图
	Name    int32  `protobuf:"varint,6,opt,name=Name,proto3" json:"Name,omitempty"`      // 名称
}

func (x *IM_Msg_Content_Video) Reset() {
	*x = IM_Msg_Content_Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content_Video) ProtoMessage() {}

func (x *IM_Msg_Content_Video) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content_Video.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content_Video) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1, 1}
}

func (x *IM_Msg_Content_Video) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *IM_Msg_Content_Video) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IM_Msg_Content_Video) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IM_Msg_Content_Video) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type IM_Msg_Content_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`          //
	Width   int32  `protobuf:"varint,2,opt,name=Width,proto3" json:"Width,omitempty"`    // 图宽
	Height  int32  `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"`  // 图高
	Size    int32  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`      // 图大小
	Content []byte `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"` // 缩略图
	Name    int32  `protobuf:"varint,6,opt,name=Name,proto3" json:"Name,omitempty"`      // 名称
}

func (x *IM_Msg_Content_Image) Reset() {
	*x = IM_Msg_Content_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content_Image) ProtoMessage() {}

func (x *IM_Msg_Content_Image) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content_Image.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content_Image) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1, 2}
}

func (x *IM_Msg_Content_Image) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *IM_Msg_Content_Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *IM_Msg_Content_Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *IM_Msg_Content_Image) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IM_Msg_Content_Image) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IM_Msg_Content_Image) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type IM_Msg_Content_Voice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *IM_Msg_Content_Voice) Reset() {
	*x = IM_Msg_Content_Voice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content_Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content_Voice) ProtoMessage() {}

func (x *IM_Msg_Content_Voice) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content_Voice.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content_Voice) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1, 3}
}

func (x *IM_Msg_Content_Voice) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type IM_Msg_Content_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`      //
	Size  int32  `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`  // 图大小
	Types string `protobuf:"bytes,3,opt,name=Types,proto3" json:"Types,omitempty"` //
	Name  int32  `protobuf:"varint,4,opt,name=Name,proto3" json:"Name,omitempty"`  // 图大小
}

func (x *IM_Msg_Content_File) Reset() {
	*x = IM_Msg_Content_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content_File) ProtoMessage() {}

func (x *IM_Msg_Content_File) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content_File.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content_File) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1, 4}
}

func (x *IM_Msg_Content_File) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *IM_Msg_Content_File) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IM_Msg_Content_File) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *IM_Msg_Content_File) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type IM_Msg_Content_Emoticon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"` // 名称
}

func (x *IM_Msg_Content_Emoticon) Reset() {
	*x = IM_Msg_Content_Emoticon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_im_proto_pb_im_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IM_Msg_Content_Emoticon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IM_Msg_Content_Emoticon) ProtoMessage() {}

func (x *IM_Msg_Content_Emoticon) ProtoReflect() protoreflect.Message {
	mi := &file_kits_im_proto_pb_im_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IM_Msg_Content_Emoticon.ProtoReflect.Descriptor instead.
func (*IM_Msg_Content_Emoticon) Descriptor() ([]byte, []int) {
	return file_kits_im_proto_pb_im_proto_rawDescGZIP(), []int{0, 0, 1, 5}
}

func (x *IM_Msg_Content_Emoticon) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IM_Msg_Content_Emoticon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_kits_im_proto_pb_im_proto protoreflect.FileDescriptor

var file_kits_im_proto_pb_im_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x69, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x62, 0x2f, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0xfa, 0x07, 0x0a, 0x02, 0x49, 0x4d, 0x1a, 0xf3, 0x07, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x1a, 0x88,
	0x04, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x65, 0x71, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x65,
	0x71, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x54, 0x6f, 0x12, 0x2d, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x12, 0x30, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x2e, 0x4d, 0x73, 0x67, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x2e, 0x4d, 0x73,
	0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x48,
	0x00, 0x52, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x2e, 0x4d,
	0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x45, 0x6d, 0x6f, 0x74, 0x69,
	0x63, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x4d, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6d,
	0x6f, 0x74, 0x69, 0x63, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x46, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x75, 0x72, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x46, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x75, 0x72, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x46, 0x53, 0x65, 0x78, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x53,
	0x65, 0x78, 0x12, 0x2a, 0x0a, 0x06, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x4d, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x54,
	0x6f, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x06, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0xc3, 0x03, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x20, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x59, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x1a, 0x87, 0x01, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x21, 0x0a, 0x05,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a,
	0x54, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x38, 0x0a, 0x08, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x1b, 0x0a, 0x07, 0x54, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x6f,
	0x43, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x6f, 0x47, 0x10, 0x01, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x61, 0x61, 0x2f, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x69, 0x6d, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kits_im_proto_pb_im_proto_rawDescOnce sync.Once
	file_kits_im_proto_pb_im_proto_rawDescData = file_kits_im_proto_pb_im_proto_rawDesc
)

func file_kits_im_proto_pb_im_proto_rawDescGZIP() []byte {
	file_kits_im_proto_pb_im_proto_rawDescOnce.Do(func() {
		file_kits_im_proto_pb_im_proto_rawDescData = protoimpl.X.CompressGZIP(file_kits_im_proto_pb_im_proto_rawDescData)
	})
	return file_kits_im_proto_pb_im_proto_rawDescData
}

var file_kits_im_proto_pb_im_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kits_im_proto_pb_im_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kits_im_proto_pb_im_proto_goTypes = []interface{}{
	(IM_Msg_ToTypes)(0),             // 0: pb.IM.Msg.ToTypes
	(*IM)(nil),                      // 1: pb.IM
	(*IM_Msg)(nil),                  // 2: pb.IM.Msg
	(*IM_Msg_Body)(nil),             // 3: pb.IM.Msg.Body
	(*IM_Msg_Content)(nil),          // 4: pb.IM.Msg.Content
	(*IM_Msg_Content_Text)(nil),     // 5: pb.IM.Msg.Content.Text
	(*IM_Msg_Content_Video)(nil),    // 6: pb.IM.Msg.Content.Video
	(*IM_Msg_Content_Image)(nil),    // 7: pb.IM.Msg.Content.Image
	(*IM_Msg_Content_Voice)(nil),    // 8: pb.IM.Msg.Content.Voice
	(*IM_Msg_Content_File)(nil),     // 9: pb.IM.Msg.Content.File
	(*IM_Msg_Content_Emoticon)(nil), // 10: pb.IM.Msg.Content.Emoticon
}
var file_kits_im_proto_pb_im_proto_depIdxs = []int32{
	5,  // 0: pb.IM.Msg.Body.Text:type_name -> pb.IM.Msg.Content.Text
	6,  // 1: pb.IM.Msg.Body.Video:type_name -> pb.IM.Msg.Content.Video
	7,  // 2: pb.IM.Msg.Body.Image:type_name -> pb.IM.Msg.Content.Image
	8,  // 3: pb.IM.Msg.Body.Voice:type_name -> pb.IM.Msg.Content.Voice
	9,  // 4: pb.IM.Msg.Body.File:type_name -> pb.IM.Msg.Content.File
	10, // 5: pb.IM.Msg.Body.Emoticon:type_name -> pb.IM.Msg.Content.Emoticon
	0,  // 6: pb.IM.Msg.Body.ToType:type_name -> pb.IM.Msg.ToTypes
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_kits_im_proto_pb_im_proto_init() }
func file_kits_im_proto_pb_im_proto_init() {
	if File_kits_im_proto_pb_im_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kits_im_proto_pb_im_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content_Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content_Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content_Voice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_im_proto_pb_im_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IM_Msg_Content_Emoticon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kits_im_proto_pb_im_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*IM_Msg_Body_Text)(nil),
		(*IM_Msg_Body_Video)(nil),
		(*IM_Msg_Body_Image)(nil),
		(*IM_Msg_Body_Voice)(nil),
		(*IM_Msg_Body_File)(nil),
		(*IM_Msg_Body_Emoticon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kits_im_proto_pb_im_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kits_im_proto_pb_im_proto_goTypes,
		DependencyIndexes: file_kits_im_proto_pb_im_proto_depIdxs,
		EnumInfos:         file_kits_im_proto_pb_im_proto_enumTypes,
		MessageInfos:      file_kits_im_proto_pb_im_proto_msgTypes,
	}.Build()
	File_kits_im_proto_pb_im_proto = out.File
	file_kits_im_proto_pb_im_proto_rawDesc = nil
	file_kits_im_proto_pb_im_proto_goTypes = nil
	file_kits_im_proto_pb_im_proto_depIdxs = nil
}
