// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: kits/usrt/proto/pb/usrt.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type USRT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *USRT) Reset() {
	*x = USRT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USRT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USRT) ProtoMessage() {}

func (x *USRT) ProtoReflect() protoreflect.Message {
	mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USRT.ProtoReflect.Descriptor instead.
func (*USRT) Descriptor() ([]byte, []int) {
	return file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP(), []int{0}
}

type USRT_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LoginType string `protobuf:"bytes,2,opt,name=LoginType,proto3" json:"LoginType,omitempty"` // 登录平台
	Addr      string `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`           // 所在网关
}

func (x *USRT_User) Reset() {
	*x = USRT_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USRT_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USRT_User) ProtoMessage() {}

func (x *USRT_User) ProtoReflect() protoreflect.Message {
	mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USRT_User.ProtoReflect.Descriptor instead.
func (*USRT_User) Descriptor() ([]byte, []int) {
	return file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP(), []int{0, 0}
}

func (x *USRT_User) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *USRT_User) GetLoginType() string {
	if x != nil {
		return x.LoginType
	}
	return ""
}

func (x *USRT_User) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type USRT_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *USRT_Status) Reset() {
	*x = USRT_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USRT_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USRT_Status) ProtoMessage() {}

func (x *USRT_Status) ProtoReflect() protoreflect.Message {
	mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USRT_Status.ProtoReflect.Descriptor instead.
func (*USRT_Status) Descriptor() ([]byte, []int) {
	return file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP(), []int{0, 1}
}

type USRT_Status_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []uint64 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *USRT_Status_Request) Reset() {
	*x = USRT_Status_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USRT_Status_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USRT_Status_Request) ProtoMessage() {}

func (x *USRT_Status_Request) ProtoReflect() protoreflect.Message {
	mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USRT_Status_Request.ProtoReflect.Descriptor instead.
func (*USRT_Status_Request) Descriptor() ([]byte, []int) {
	return file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *USRT_Status_Request) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type USRT_Status_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*USRT_User `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *USRT_Status_Update) Reset() {
	*x = USRT_Status_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USRT_Status_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USRT_Status_Update) ProtoMessage() {}

func (x *USRT_Status_Update) ProtoReflect() protoreflect.Message {
	mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USRT_Status_Update.ProtoReflect.Descriptor instead.
func (*USRT_Status_Update) Descriptor() ([]byte, []int) {
	return file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *USRT_Status_Update) GetValues() []*USRT_User {
	if x != nil {
		return x.Values
	}
	return nil
}

type USRT_Status_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*USRT_User `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *USRT_Status_Reply) Reset() {
	*x = USRT_Status_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USRT_Status_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USRT_Status_Reply) ProtoMessage() {}

func (x *USRT_Status_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_kits_usrt_proto_pb_usrt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USRT_Status_Reply.ProtoReflect.Descriptor instead.
func (*USRT_Status_Reply) Descriptor() ([]byte, []int) {
	return file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *USRT_Status_Reply) GetValues() []*USRT_User {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_kits_usrt_proto_pb_usrt_proto protoreflect.FileDescriptor

var file_kits_usrt_proto_pb_usrt_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x75, 0x73, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xdf, 0x01, 0x0a, 0x04, 0x55, 0x53, 0x52, 0x54, 0x1a, 0x48, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x1a, 0x8c, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x1a, 0x2f, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25,
	0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x53, 0x52, 0x54, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x2e, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25,
	0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x53, 0x52, 0x54, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x61, 0x61,
	0x2f, 0x6b, 0x69, 0x74, 0x73, 0x2f, 0x75, 0x73, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kits_usrt_proto_pb_usrt_proto_rawDescOnce sync.Once
	file_kits_usrt_proto_pb_usrt_proto_rawDescData = file_kits_usrt_proto_pb_usrt_proto_rawDesc
)

func file_kits_usrt_proto_pb_usrt_proto_rawDescGZIP() []byte {
	file_kits_usrt_proto_pb_usrt_proto_rawDescOnce.Do(func() {
		file_kits_usrt_proto_pb_usrt_proto_rawDescData = protoimpl.X.CompressGZIP(file_kits_usrt_proto_pb_usrt_proto_rawDescData)
	})
	return file_kits_usrt_proto_pb_usrt_proto_rawDescData
}

var file_kits_usrt_proto_pb_usrt_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kits_usrt_proto_pb_usrt_proto_goTypes = []interface{}{
	(*USRT)(nil),                // 0: pb.USRT
	(*USRT_User)(nil),           // 1: pb.USRT.User
	(*USRT_Status)(nil),         // 2: pb.USRT.Status
	(*USRT_Status_Request)(nil), // 3: pb.USRT.Status.Request
	(*USRT_Status_Update)(nil),  // 4: pb.USRT.Status.Update
	(*USRT_Status_Reply)(nil),   // 5: pb.USRT.Status.Reply
}
var file_kits_usrt_proto_pb_usrt_proto_depIdxs = []int32{
	1, // 0: pb.USRT.Status.Update.Values:type_name -> pb.USRT.User
	1, // 1: pb.USRT.Status.Reply.Values:type_name -> pb.USRT.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kits_usrt_proto_pb_usrt_proto_init() }
func file_kits_usrt_proto_pb_usrt_proto_init() {
	if File_kits_usrt_proto_pb_usrt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kits_usrt_proto_pb_usrt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USRT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_usrt_proto_pb_usrt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USRT_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_usrt_proto_pb_usrt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USRT_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_usrt_proto_pb_usrt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USRT_Status_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_usrt_proto_pb_usrt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USRT_Status_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kits_usrt_proto_pb_usrt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USRT_Status_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kits_usrt_proto_pb_usrt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kits_usrt_proto_pb_usrt_proto_goTypes,
		DependencyIndexes: file_kits_usrt_proto_pb_usrt_proto_depIdxs,
		MessageInfos:      file_kits_usrt_proto_pb_usrt_proto_msgTypes,
	}.Build()
	File_kits_usrt_proto_pb_usrt_proto = out.File
	file_kits_usrt_proto_pb_usrt_proto_rawDesc = nil
	file_kits_usrt_proto_pb_usrt_proto_goTypes = nil
	file_kits_usrt_proto_pb_usrt_proto_depIdxs = nil
}
