// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.1
// source: internal/proto/pb/sm.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SM_Action int32

const (
	SM_ActionUserStatusUpdate SM_Action = 0
	SM_ActionUserOnline       SM_Action = 1
	SM_ActionUserOffline      SM_Action = 2
	SM_ActionUserCleanCache   SM_Action = 3
)

// Enum value maps for SM_Action.
var (
	SM_Action_name = map[int32]string{
		0: "ActionUserStatusUpdate",
		1: "ActionUserOnline",
		2: "ActionUserOffline",
		3: "ActionUserCleanCache",
	}
	SM_Action_value = map[string]int32{
		"ActionUserStatusUpdate": 0,
		"ActionUserOnline":       1,
		"ActionUserOffline":      2,
		"ActionUserCleanCache":   3,
	}
)

func (x SM_Action) Enum() *SM_Action {
	p := new(SM_Action)
	*p = x
	return p
}

func (x SM_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SM_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_pb_sm_proto_enumTypes[0].Descriptor()
}

func (SM_Action) Type() protoreflect.EnumType {
	return &file_internal_proto_pb_sm_proto_enumTypes[0]
}

func (x SM_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SM_Action.Descriptor instead.
func (SM_Action) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 0}
}

type SM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SM) Reset() {
	*x = SM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM) ProtoMessage() {}

func (x *SM) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM.ProtoReflect.Descriptor instead.
func (*SM) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0}
}

type SM_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action SM_Action `protobuf:"varint,1,opt,name=Action,proto3,enum=pb.SM_Action" json:"Action,omitempty"`
	Data   []byte    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SM_Event) Reset() {
	*x = SM_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_Event) ProtoMessage() {}

func (x *SM_Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_Event.ProtoReflect.Descriptor instead.
func (*SM_Event) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SM_Event) GetAction() SM_Action {
	if x != nil {
		return x.Action
	}
	return SM_ActionUserStatusUpdate
}

func (x *SM_Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SM_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SM_User) Reset() {
	*x = SM_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User) ProtoMessage() {}

func (x *SM_User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User.ProtoReflect.Descriptor instead.
func (*SM_User) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1}
}

type SM_Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SM_Broadcast) Reset() {
	*x = SM_Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_Broadcast) ProtoMessage() {}

func (x *SM_Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_Broadcast.ProtoReflect.Descriptor instead.
func (*SM_Broadcast) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 2}
}

type SM_User_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	AgentServer string `protobuf:"bytes,2,opt,name=AgentServer,proto3" json:"AgentServer,omitempty"`
	Platform    string `protobuf:"bytes,3,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Token       string `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	OnlineAt    int64  `protobuf:"varint,5,opt,name=OnlineAt,proto3" json:"OnlineAt,omitempty"`
	IMServer    string `protobuf:"bytes,6,opt,name=IMServer,proto3" json:"IMServer,omitempty"`
	IDServer    string `protobuf:"bytes,7,opt,name=IDServer,proto3" json:"IDServer,omitempty"`
	PeerId      string `protobuf:"bytes,8,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
}

func (x *SM_User_Info) Reset() {
	*x = SM_User_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Info) ProtoMessage() {}

func (x *SM_User_Info) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Info.ProtoReflect.Descriptor instead.
func (*SM_User_Info) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *SM_User_Info) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SM_User_Info) GetAgentServer() string {
	if x != nil {
		return x.AgentServer
	}
	return ""
}

func (x *SM_User_Info) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SM_User_Info) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SM_User_Info) GetOnlineAt() int64 {
	if x != nil {
		return x.OnlineAt
	}
	return 0
}

func (x *SM_User_Info) GetIMServer() string {
	if x != nil {
		return x.IMServer
	}
	return ""
}

func (x *SM_User_Info) GetIDServer() string {
	if x != nil {
		return x.IDServer
	}
	return ""
}

func (x *SM_User_Info) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type SM_User_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64          `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Values []*SM_User_Info `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Status) Reset() {
	*x = SM_User_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Status) ProtoMessage() {}

func (x *SM_User_Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Status.ProtoReflect.Descriptor instead.
func (*SM_User_Status) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *SM_User_Status) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SM_User_Status) GetValues() []*SM_User_Info {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_User_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SM_User_Action) Reset() {
	*x = SM_User_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Action) ProtoMessage() {}

func (x *SM_User_Action) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Action.ProtoReflect.Descriptor instead.
func (*SM_User_Action) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 2}
}

type SM_User_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []uint64 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Request) Reset() {
	*x = SM_User_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Request) ProtoMessage() {}

func (x *SM_User_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Request.ProtoReflect.Descriptor instead.
func (*SM_User_Request) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 3}
}

func (x *SM_User_Request) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_User_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*SM_User_Status `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Reply) Reset() {
	*x = SM_User_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Reply) ProtoMessage() {}

func (x *SM_User_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Reply.ProtoReflect.Descriptor instead.
func (*SM_User_Reply) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 4}
}

func (x *SM_User_Reply) GetValues() []*SM_User_Status {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_User_Servers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SM_User_Servers) Reset() {
	*x = SM_User_Servers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers) ProtoMessage() {}

func (x *SM_User_Servers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers.ProtoReflect.Descriptor instead.
func (*SM_User_Servers) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5}
}

type SM_User_Action_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*SM_User_Status `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SM_User_Action_Update) Reset() {
	*x = SM_User_Action_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Action_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Action_Update) ProtoMessage() {}

func (x *SM_User_Action_Update) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Action_Update.ProtoReflect.Descriptor instead.
func (*SM_User_Action_Update) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 2, 0}
}

func (x *SM_User_Action_Update) GetData() []*SM_User_Status {
	if x != nil {
		return x.Data
	}
	return nil
}

type SM_User_Action_Online struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Platform string `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Agent    string `protobuf:"bytes,3,opt,name=Agent,proto3" json:"Agent,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	PeerId   string `protobuf:"bytes,5,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
}

func (x *SM_User_Action_Online) Reset() {
	*x = SM_User_Action_Online{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Action_Online) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Action_Online) ProtoMessage() {}

func (x *SM_User_Action_Online) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Action_Online.ProtoReflect.Descriptor instead.
func (*SM_User_Action_Online) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 2, 1}
}

func (x *SM_User_Action_Online) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SM_User_Action_Online) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SM_User_Action_Online) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SM_User_Action_Online) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SM_User_Action_Online) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type SM_User_Action_Offline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Platform string `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	PeerId   string `protobuf:"bytes,3,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
}

func (x *SM_User_Action_Offline) Reset() {
	*x = SM_User_Action_Offline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Action_Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Action_Offline) ProtoMessage() {}

func (x *SM_User_Action_Offline) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Action_Offline.ProtoReflect.Descriptor instead.
func (*SM_User_Action_Offline) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 2, 2}
}

func (x *SM_User_Action_Offline) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SM_User_Action_Offline) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SM_User_Action_Offline) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type SM_User_Action_CleanCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *SM_User_Action_CleanCache) Reset() {
	*x = SM_User_Action_CleanCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Action_CleanCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Action_CleanCache) ProtoMessage() {}

func (x *SM_User_Action_CleanCache) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Action_CleanCache.ProtoReflect.Descriptor instead.
func (*SM_User_Action_CleanCache) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 2, 3}
}

func (x *SM_User_Action_CleanCache) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SM_User_Servers_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64            `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Servers map[string]string `protobuf:"bytes,2,rep,name=Servers,proto3" json:"Servers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SM_User_Servers_Info) Reset() {
	*x = SM_User_Servers_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers_Info) ProtoMessage() {}

func (x *SM_User_Servers_Info) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers_Info.ProtoReflect.Descriptor instead.
func (*SM_User_Servers_Info) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5, 0}
}

func (x *SM_User_Servers_Info) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SM_User_Servers_Info) GetServers() map[string]string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type SM_User_Servers_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []uint64 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Servers_Request) Reset() {
	*x = SM_User_Servers_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers_Request) ProtoMessage() {}

func (x *SM_User_Servers_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers_Request.ProtoReflect.Descriptor instead.
func (*SM_User_Servers_Request) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5, 1}
}

func (x *SM_User_Servers_Request) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_User_Servers_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*SM_User_Servers_Info `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Servers_Reply) Reset() {
	*x = SM_User_Servers_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers_Reply) ProtoMessage() {}

func (x *SM_User_Servers_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers_Reply.ProtoReflect.Descriptor instead.
func (*SM_User_Servers_Reply) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5, 2}
}

func (x *SM_User_Servers_Reply) GetValues() []*SM_User_Servers_Info {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_User_Servers_Assign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KitName string `protobuf:"bytes,2,opt,name=KitName,proto3" json:"KitName,omitempty"`
	LB      int32  `protobuf:"varint,3,opt,name=LB,proto3" json:"LB,omitempty"`
}

func (x *SM_User_Servers_Assign) Reset() {
	*x = SM_User_Servers_Assign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers_Assign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers_Assign) ProtoMessage() {}

func (x *SM_User_Servers_Assign) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers_Assign.ProtoReflect.Descriptor instead.
func (*SM_User_Servers_Assign) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5, 3}
}

func (x *SM_User_Servers_Assign) GetKitName() string {
	if x != nil {
		return x.KitName
	}
	return ""
}

func (x *SM_User_Servers_Assign) GetLB() int32 {
	if x != nil {
		return x.LB
	}
	return 0
}

type SM_User_Servers_AssignServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64                    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Values []*SM_User_Servers_Assign `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Servers_AssignServerRequest) Reset() {
	*x = SM_User_Servers_AssignServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers_AssignServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers_AssignServerRequest) ProtoMessage() {}

func (x *SM_User_Servers_AssignServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers_AssignServerRequest.ProtoReflect.Descriptor instead.
func (*SM_User_Servers_AssignServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5, 4}
}

func (x *SM_User_Servers_AssignServerRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SM_User_Servers_AssignServerRequest) GetValues() []*SM_User_Servers_Assign {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_User_Servers_AssignServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId map[string]string     `protobuf:"bytes,1,rep,name=PeerId,proto3" json:"PeerId,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Values *SM_User_Servers_Info `protobuf:"bytes,2,opt,name=Values,proto3" json:"Values,omitempty"`
}

func (x *SM_User_Servers_AssignServerReply) Reset() {
	*x = SM_User_Servers_AssignServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_User_Servers_AssignServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_User_Servers_AssignServerReply) ProtoMessage() {}

func (x *SM_User_Servers_AssignServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_User_Servers_AssignServerReply.ProtoReflect.Descriptor instead.
func (*SM_User_Servers_AssignServerReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 1, 5, 5}
}

func (x *SM_User_Servers_AssignServerReply) GetPeerId() map[string]string {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *SM_User_Servers_AssignServerReply) GetValues() *SM_User_Servers_Info {
	if x != nil {
		return x.Values
	}
	return nil
}

type SM_Broadcast_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    int32    `protobuf:"varint,1,opt,name=Command,proto3" json:"Command,omitempty"`
	SubCommand int32    `protobuf:"varint,2,opt,name=SubCommand,proto3" json:"SubCommand,omitempty"`
	Payload    []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Receiver   []uint64 `protobuf:"varint,4,rep,packed,name=Receiver,proto3" json:"Receiver,omitempty"`
}

func (x *SM_Broadcast_Message) Reset() {
	*x = SM_Broadcast_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_Broadcast_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_Broadcast_Message) ProtoMessage() {}

func (x *SM_Broadcast_Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_Broadcast_Message.ProtoReflect.Descriptor instead.
func (*SM_Broadcast_Message) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *SM_Broadcast_Message) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *SM_Broadcast_Message) GetSubCommand() int32 {
	if x != nil {
		return x.SubCommand
	}
	return 0
}

func (x *SM_Broadcast_Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SM_Broadcast_Message) GetReceiver() []uint64 {
	if x != nil {
		return x.Receiver
	}
	return nil
}

type SM_Broadcast_Messages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*SM_Broadcast_Message `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	Sync   bool                    `protobuf:"varint,2,opt,name=Sync,proto3" json:"Sync,omitempty"`
}

func (x *SM_Broadcast_Messages) Reset() {
	*x = SM_Broadcast_Messages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_Broadcast_Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_Broadcast_Messages) ProtoMessage() {}

func (x *SM_Broadcast_Messages) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_Broadcast_Messages.ProtoReflect.Descriptor instead.
func (*SM_Broadcast_Messages) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *SM_Broadcast_Messages) GetValues() []*SM_Broadcast_Message {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SM_Broadcast_Messages) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type SM_Broadcast_Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successed []uint64 `protobuf:"varint,1,rep,packed,name=Successed,proto3" json:"Successed,omitempty"`
	Failed    []uint64 `protobuf:"varint,2,rep,packed,name=Failed,proto3" json:"Failed,omitempty"`
}

func (x *SM_Broadcast_Ack) Reset() {
	*x = SM_Broadcast_Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_sm_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_Broadcast_Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_Broadcast_Ack) ProtoMessage() {}

func (x *SM_Broadcast_Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_sm_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_Broadcast_Ack.ProtoReflect.Descriptor instead.
func (*SM_Broadcast_Ack) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_sm_proto_rawDescGZIP(), []int{0, 2, 2}
}

func (x *SM_Broadcast_Ack) GetSuccessed() []uint64 {
	if x != nil {
		return x.Successed
	}
	return nil
}

func (x *SM_Broadcast_Ack) GetFailed() []uint64 {
	if x != nil {
		return x.Failed
	}
	return nil
}

var File_internal_proto_pb_sm_proto protoreflect.FileDescriptor

var file_internal_proto_pb_sm_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x85, 0x0e, 0x0a, 0x02, 0x53, 0x4d, 0x1a, 0x42, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0xb5, 0x0a, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x1a, 0xde, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x44, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x44, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x4a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x1a, 0xba, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x30, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x80,
	0x01, 0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49,
	0x64, 0x1a, 0x55, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x24, 0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x21,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x1a, 0x33, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x4d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0xea, 0x04, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x1a, 0x9b, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x06,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x4d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x32,
	0x0a, 0x06, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x69, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4b, 0x69, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4c, 0x42, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x4c, 0x42, 0x1a, 0x61, 0x0a, 0x13, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x32, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x06, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0xcb, 0x01, 0x0a, 0x11, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x06, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x4d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06,
	0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x50, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x95, 0x02, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x1a, 0x79, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x75, 0x62, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x1a, 0x50, 0x0a, 0x08,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x4d,
	0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x79,
	0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x1a, 0x3b,
	0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x6b, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x02, 0x12, 0x18,
	0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x10, 0x03, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x6f, 0x2f,
	0x62, 0x61, 0x61, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_pb_sm_proto_rawDescOnce sync.Once
	file_internal_proto_pb_sm_proto_rawDescData = file_internal_proto_pb_sm_proto_rawDesc
)

func file_internal_proto_pb_sm_proto_rawDescGZIP() []byte {
	file_internal_proto_pb_sm_proto_rawDescOnce.Do(func() {
		file_internal_proto_pb_sm_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_pb_sm_proto_rawDescData)
	})
	return file_internal_proto_pb_sm_proto_rawDescData
}

var file_internal_proto_pb_sm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_pb_sm_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_internal_proto_pb_sm_proto_goTypes = []interface{}{
	(SM_Action)(0),                              // 0: pb.SM.Action
	(*SM)(nil),                                  // 1: pb.SM
	(*SM_Event)(nil),                            // 2: pb.SM.Event
	(*SM_User)(nil),                             // 3: pb.SM.User
	(*SM_Broadcast)(nil),                        // 4: pb.SM.Broadcast
	(*SM_User_Info)(nil),                        // 5: pb.SM.User.Info
	(*SM_User_Status)(nil),                      // 6: pb.SM.User.Status
	(*SM_User_Action)(nil),                      // 7: pb.SM.User.Action
	(*SM_User_Request)(nil),                     // 8: pb.SM.User.Request
	(*SM_User_Reply)(nil),                       // 9: pb.SM.User.Reply
	(*SM_User_Servers)(nil),                     // 10: pb.SM.User.Servers
	(*SM_User_Action_Update)(nil),               // 11: pb.SM.User.Action.Update
	(*SM_User_Action_Online)(nil),               // 12: pb.SM.User.Action.Online
	(*SM_User_Action_Offline)(nil),              // 13: pb.SM.User.Action.Offline
	(*SM_User_Action_CleanCache)(nil),           // 14: pb.SM.User.Action.CleanCache
	(*SM_User_Servers_Info)(nil),                // 15: pb.SM.User.Servers.Info
	(*SM_User_Servers_Request)(nil),             // 16: pb.SM.User.Servers.Request
	(*SM_User_Servers_Reply)(nil),               // 17: pb.SM.User.Servers.Reply
	(*SM_User_Servers_Assign)(nil),              // 18: pb.SM.User.Servers.Assign
	(*SM_User_Servers_AssignServerRequest)(nil), // 19: pb.SM.User.Servers.AssignServerRequest
	(*SM_User_Servers_AssignServerReply)(nil),   // 20: pb.SM.User.Servers.AssignServerReply
	nil,                           // 21: pb.SM.User.Servers.Info.ServersEntry
	nil,                           // 22: pb.SM.User.Servers.AssignServerReply.PeerIdEntry
	(*SM_Broadcast_Message)(nil),  // 23: pb.SM.Broadcast.Message
	(*SM_Broadcast_Messages)(nil), // 24: pb.SM.Broadcast.Messages
	(*SM_Broadcast_Ack)(nil),      // 25: pb.SM.Broadcast.Ack
}
var file_internal_proto_pb_sm_proto_depIdxs = []int32{
	0,  // 0: pb.SM.Event.Action:type_name -> pb.SM.Action
	5,  // 1: pb.SM.User.Status.Values:type_name -> pb.SM.User.Info
	6,  // 2: pb.SM.User.Reply.Values:type_name -> pb.SM.User.Status
	6,  // 3: pb.SM.User.Action.Update.Data:type_name -> pb.SM.User.Status
	21, // 4: pb.SM.User.Servers.Info.Servers:type_name -> pb.SM.User.Servers.Info.ServersEntry
	15, // 5: pb.SM.User.Servers.Reply.Values:type_name -> pb.SM.User.Servers.Info
	18, // 6: pb.SM.User.Servers.AssignServerRequest.Values:type_name -> pb.SM.User.Servers.Assign
	22, // 7: pb.SM.User.Servers.AssignServerReply.PeerId:type_name -> pb.SM.User.Servers.AssignServerReply.PeerIdEntry
	15, // 8: pb.SM.User.Servers.AssignServerReply.Values:type_name -> pb.SM.User.Servers.Info
	23, // 9: pb.SM.Broadcast.Messages.Values:type_name -> pb.SM.Broadcast.Message
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_proto_pb_sm_proto_init() }
func file_internal_proto_pb_sm_proto_init() {
	if File_internal_proto_pb_sm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_pb_sm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Action_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Action_Online); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Action_Offline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Action_CleanCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers_Assign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers_AssignServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_User_Servers_AssignServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_Broadcast_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_Broadcast_Messages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_sm_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_Broadcast_Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_pb_sm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_pb_sm_proto_goTypes,
		DependencyIndexes: file_internal_proto_pb_sm_proto_depIdxs,
		EnumInfos:         file_internal_proto_pb_sm_proto_enumTypes,
		MessageInfos:      file_internal_proto_pb_sm_proto_msgTypes,
	}.Build()
	File_internal_proto_pb_sm_proto = out.File
	file_internal_proto_pb_sm_proto_rawDesc = nil
	file_internal_proto_pb_sm_proto_goTypes = nil
	file_internal_proto_pb_sm_proto_depIdxs = nil
}
